import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "bn" | "en";

interface Translations {
  [key: string]: { bn: string; en: string };
}

export const translations: Translations = {
  // Nav
  home: { bn: "হোম", en: "Home" },
  blog: { bn: "ব্লগ", en: "Blog" },
  events: { bn: "ইভেন্ট", en: "Events" },
  courses: { bn: "কোর্স", en: "Courses" },
  members: { bn: "সদস্য", en: "Members" },
  about: { bn: "আমাদের সম্পর্কে", en: "About Us" },
  services: { bn: "সেবাসমূহ", en: "Services" },
  contact: { bn: "যোগাযোগ", en: "Contact" },
  login: { bn: "লগইন", en: "Login" },
  signup: { bn: "রেজিস্ট্রেশন", en: "Sign Up" },
  search: { bn: "অনুসন্ধান...", en: "Search..." },
  subscribe: { bn: "সাবস্ক্রাইব করুন", en: "Subscribe" },
  joinUs: { bn: "যোগ দিন", en: "Join Us" },
  profile: { bn: "প্রোফাইল", en: "Profile" },
  adminPanel: { bn: "অ্যাডমিন প্যানেল", en: "Admin Panel" },
  settings: { bn: "সেটিংস", en: "Settings" },
  logout: { bn: "লগআউট", en: "Logout" },
  // Home page
  latestPosts: { bn: "সাম্প্রতিক পোস্ট", en: "Latest Posts" },
  upcomingEvents: { bn: "আসন্ন ইভেন্ট", en: "Upcoming Events" },
  notices: { bn: "বিজ্ঞপ্তি", en: "Notices" },
  viewAll: { bn: "সব দেখুন", en: "View All" },
  // Footer
  quickLinks: { bn: "দ্রুত লিঙ্ক", en: "Quick Links" },
  contactInfo: { bn: "যোগাযোগ", en: "Contact" },
  emailSubscribe: { bn: "নিউজলেটার", en: "Newsletter" },
  subscribeDesc: { bn: "আমাদের সর্বশেষ খবর ও ইভেন্টের আপডেট পেতে সাবস্ক্রাইব করুন।", en: "Subscribe to get our latest news and event updates." },
  yourEmail: { bn: "আপনার ইমেইল", en: "Your email" },
  copyright: { bn: "© ২০২৬ ফরিদপুর সাহিত্য পরিষদ। সর্বস্বত্ব সংরক্ষিত।", en: "© 2026 Faridpur Shahitto Parishad. All rights reserved." },
  madeWith: { bn: "বাংলাদেশে তৈরি", en: "Made in Bangladesh" },
  backToHome: { bn: "হোমে ফিরে যান", en: "Back to Home" },
  readMore: { bn: "বিস্তারিত দেখুন", en: "Read More" },
  register: { bn: "নিবন্ধন করুন", en: "Register" },
  // Members
  seniorMembers: { bn: "সিনিয়র সদস্যবৃন্দ", en: "Senior Members" },
  generalMembers: { bn: "সাধারণ সদস্যবৃন্দ", en: "General Members" },
  membersSubtitle: { bn: "আমাদের সংগঠনের সিনিয়র ও সাধারণ সদস্যবৃন্দ", en: "Senior and general members of our organization" },
  // Hero
  heroTitle: { bn: "ফরিদপুর সাহিত্য পরিষদ", en: "Faridpur Shahitto Parishad" },
  heroSubtitle: { bn: "সাহিত্য, সংস্কৃতি ও জ্ঞানচর্চার মাধ্যমে বাংলার ঐতিহ্য সংরক্ষণ ও বিকাশে নিবেদিত", en: "Dedicated to preserving and enriching Bengali heritage through literature, culture & knowledge" },
  heroTagline: { bn: "বাংলা সংস্কৃতির পাদপীঠ", en: "The Cradle of Bengali Culture" },
  visitors: { bn: "জন পরিদর্শক", en: "Visitors" },
  learnAbout: { bn: "আমাদের সম্পর্কে জানুন", en: "Learn About Us" },
  viewMembers: { bn: "সদস্যবৃন্দ দেখুন", en: "View Members" },
  exploreHome: { bn: "হোম পেজ দেখুন", en: "Explore Home" },
  // Page titles
  blogAndPosts: { bn: "ব্লগ ও পোস্ট", en: "Blog & Posts" },
  allEvents: { bn: "ইভেন্ট সমূহ", en: "All Events" },
  allCourses: { bn: "কোর্স সমূহ", en: "Courses" },
  allMembers: { bn: "সদস্যবৃন্দ", en: "Members" },
  // Auth
  password: { bn: "পাসওয়ার্ড", en: "Password" },
  fullName: { bn: "পূর্ণ নাম", en: "Full Name" },
  emailOrPhone: { bn: "ইমেইল বা ফোন নম্বর", en: "Email or Phone" },
  phone: { bn: "ফোন নম্বর", en: "Phone Number" },
  rememberMe: { bn: "মনে রাখুন", en: "Remember me" },
  forgotPassword: { bn: "পাসওয়ার্ড ভুলেছেন?", en: "Forgot password?" },
  orContinueWith: { bn: "অথবা", en: "or" },
  continueWithGoogle: { bn: "Google দিয়ে চালিয়ে যান", en: "Continue with Google" },
  noAccount: { bn: "একাউন্ট নেই?", en: "Don't have an account?" },
  hasAccount: { bn: "একাউন্ট আছে?", en: "Already have an account?" },
  loginTitle: { bn: "লগইন করুন", en: "Login" },
  signupTitle: { bn: "নতুন একাউন্ট তৈরি করুন", en: "Create New Account" },
  loginSubtitle: { bn: "আপনার একাউন্টে প্রবেশ করুন", en: "Sign in to your account" },
  signupSubtitle: { bn: "আমাদের সাহিত্য পরিবারে যোগ দিন", en: "Join our literary family" },
  loginFailed: { bn: "লগইন ব্যর্থ", en: "Login failed" },
  signupFailed: { bn: "রেজিস্ট্রেশন ব্যর্থ", en: "Registration failed" },
  signupSuccess: { bn: "সফল!", en: "Success!" },
  checkEmail: { bn: "অনুগ্রহ করে আপনার ইমেইল যাচাই করুন।", en: "Please check your email for verification." },
  googleLoginFailed: { bn: "Google লগইন ব্যর্থ", en: "Google login failed" },
  // Forgot / Reset password
  forgotPasswordTitle: { bn: "পাসওয়ার্ড পুনরুদ্ধার", en: "Password Recovery" },
  forgotPasswordSubtitle: { bn: "আপনার ইমেইল দিন, আমরা রিসেট লিংক পাঠাবো", en: "Enter your email and we'll send a reset link" },
  sendResetLink: { bn: "রিসেট লিংক পাঠান", en: "Send Reset Link" },
  resetLinkSent: { bn: "রিসেট লিংক পাঠানো হয়েছে", en: "Reset link sent" },
  resetLinkSentDesc: { bn: "আপনার ইমেইলে পাসওয়ার্ড রিসেট লিংক পাঠানো হয়েছে।", en: "A password reset link has been sent to your email." },
  resetPasswordTitle: { bn: "নতুন পাসওয়ার্ড সেট করুন", en: "Set New Password" },
  resetPasswordSubtitle: { bn: "আপনার নতুন পাসওয়ার্ড দিন", en: "Enter your new password" },
  newPassword: { bn: "নতুন পাসওয়ার্ড", en: "New Password" },
  confirmPassword: { bn: "পাসওয়ার্ড নিশ্চিত করুন", en: "Confirm Password" },
  updatePassword: { bn: "পাসওয়ার্ড আপডেট করুন", en: "Update Password" },
  passwordUpdated: { bn: "পাসওয়ার্ড আপডেট হয়েছে", en: "Password updated" },
  passwordUpdatedDesc: { bn: "আপনার পাসওয়ার্ড সফলভাবে আপডেট হয়েছে।", en: "Your password has been updated successfully." },
  passwordMismatch: { bn: "পাসওয়ার্ড মিলছে না", en: "Passwords don't match" },
  backToLogin: { bn: "লগইনে ফিরে যান", en: "Back to Login" },
  email: { bn: "ইমেইল", en: "Email" },
  // About section
  aboutIdentity: { bn: "আমাদের পরিচয়", en: "Our Identity" },
  aboutTitle: { bn: "সাহিত্য ও সংস্কৃতির পথে", en: "The Path of Literature & Culture" },
  aboutDesc: { bn: "ফরিদপুর সাহিত্য পরিষদ বাংলাদেশের ফরিদপুর জেলার একটি ঐতিহ্যবাহী সাংস্কৃতিক সংগঠন। সাহিত্যচর্চা, সাংস্কৃতিক কর্মকাণ্ড ও সামাজিক উন্নয়নে আমরা নিরলসভাবে কাজ করে যাচ্ছি।", en: "Faridpur Shahitto Parishad is a historic cultural organization of Faridpur district, Bangladesh. We are tirelessly working towards literary pursuits, cultural activities, and social development." },
  publications: { bn: "প্রকাশিত সাহিত্য", en: "Publications" },
  activeMembers: { bn: "সক্রিয় সদস্য", en: "Active Members" },
  annualEvents: { bn: "বার্ষিক অনুষ্ঠান", en: "Annual Events" },
  yearsLegacy: { bn: "বছরের ঐতিহ্য", en: "Years of Legacy" },
  // Services section
  ourActivities: { bn: "আমাদের কার্যক্রম", en: "Our Activities" },
  servicesTitle: { bn: "সেবা ও কার্যক্রম", en: "Services & Activities" },
  svcLitPub: { bn: "সাহিত্য প্রকাশনা", en: "Literary Publications" },
  svcLitPubDesc: { bn: "কবিতা, গল্প, উপন্যাস ও প্রবন্ধ সংকলন প্রকাশ ও পাঠচক্র আয়োজন", en: "Publishing poetry, stories, novels, essays and organizing reading circles" },
  svcCultural: { bn: "সাংস্কৃতিক অনুষ্ঠান", en: "Cultural Events" },
  svcCulturalDesc: { bn: "আবৃত্তি, নাটক, সংগীত ও নৃত্য পরিবেশনা সহ বিভিন্ন সাংস্কৃতিক অনুষ্ঠান", en: "Recitation, drama, music and dance performances along with various cultural events" },
  svcEducation: { bn: "শিক্ষা কার্যক্রম", en: "Educational Programs" },
  svcEducationDesc: { bn: "ভাষা শিক্ষা, সেমিনার ও কর্মশালার মাধ্যমে জ্ঞানের আলো ছড়ানো", en: "Spreading the light of knowledge through language education, seminars, and workshops" },
  svcArts: { bn: "শিল্পকলা", en: "Arts & Crafts" },
  svcArtsDesc: { bn: "চিত্রকলা, ভাস্কর্য ও হস্তশিল্পের প্রদর্শনী ও প্রশিক্ষণ", en: "Exhibitions and training in painting, sculpture, and handicrafts" },
  svcCommunity: { bn: "সামাজিক উন্নয়ন", en: "Community Development" },
  svcCommunityDesc: { bn: "সমাজসেবা, সচেতনতামূলক প্রচারণা ও গণশিক্ষা কার্যক্রম", en: "Social services, awareness campaigns, and public education programs" },
  svcHeritage: { bn: "ঐতিহ্য সংরক্ষণ", en: "Heritage Preservation" },
  svcHeritageDesc: { bn: "বাংলার লোকসংস্কৃতি, ঐতিহ্য ও ইতিহাস সংরক্ষণ ও গবেষণা", en: "Preservation and research of Bengali folk culture, heritage, and history" },
  // Events preview
  eventSchedule: { bn: "অনুষ্ঠানসূচি", en: "Event Schedule" },
  upcomingEventsTitle: { bn: "আসন্ন ইভেন্ট", en: "Upcoming Events" },
  // Members section
  ourLeadership: { bn: "আমাদের নেতৃত্ব", en: "Our Leadership" },
  // Footer
  orgDesc: { bn: "সাহিত্য, সংস্কৃতি ও জ্ঞানচর্চার মাধ্যমে বাংলার ঐতিহ্য সংরক্ষণ ও বিকাশে নিবেদিত একটি সাংস্কৃতিক সংগঠন।", en: "A cultural organization dedicated to preserving and enriching Bengali heritage through literature, culture, and knowledge." },
  footerHomePage: { bn: "হোম পেজ", en: "Home Page" },
  footerBlog: { bn: "ব্লগ ও পোস্ট", en: "Blog & Posts" },
  footerEvents: { bn: "ইভেন্ট সমূহ", en: "Events" },
  footerProjects: { bn: "প্রজেক্ট", en: "Projects" },
  footerCourses: { bn: "কোর্স সমূহ", en: "Courses" },
  footerMembers: { bn: "সদস্যবৃন্দ", en: "Members" },
  // Blog
  blogSearchPlaceholder: { bn: "পোস্ট অনুসন্ধান করুন...", en: "Search posts..." },
  blogSubtitle: { bn: "সাহিত্য, সংস্কৃতি ও জ্ঞানের বিভিন্ন বিষয়ে আমাদের লেখা সমূহ", en: "Our writings on various topics of literature, culture and knowledge" },
  noPosts: { bn: "কোনো পোস্ট পাওয়া যায়নি", en: "No posts found" },
  featured: { bn: "বিশেষ", en: "Featured" },
  // Events page
  eventsPageSubtitle: { bn: "আমাদের সাংস্কৃতিক অনুষ্ঠান ও কর্মসূচি", en: "Our cultural events and programs" },
  noEvents: { bn: "কোনো ইভেন্ট পাওয়া যায়নি", en: "No events found" },
  // Categories
  catAll: { bn: "সব", en: "All" },
  catLiterature: { bn: "সাহিত্য", en: "Literature" },
  catCulture: { bn: "সংস্কৃতি", en: "Culture" },
  catDrama: { bn: "নাটক", en: "Drama" },
  catFestival: { bn: "উৎসব", en: "Festival" },
  // Category map values (for translating category stored in DB/mock as Bengali)
  "সাহিত্য": { bn: "সাহিত্য", en: "Literature" },
  "সংস্কৃতি": { bn: "সংস্কৃতি", en: "Culture" },
  "নাটক": { bn: "নাটক", en: "Drama" },
  "উৎসব": { bn: "উৎসব", en: "Festival" },
  // Event tags
  "আসন্ন": { bn: "আসন্ন", en: "Upcoming" },
  "নিবন্ধন চলছে": { bn: "নিবন্ধন চলছে", en: "Registration Open" },
  "শীঘ্রই": { bn: "শীঘ্রই", en: "Soon" },
  // Mock post dates
  "২০ মার্চ, ২০২৬": { bn: "২০ মার্চ, ২০২৬", en: "March 20, 2026" },
  "১৫ মার্চ, ২০২৬": { bn: "১৫ মার্চ, ২০২৬", en: "March 15, 2026" },
  "১০ মার্চ, ২০২৬": { bn: "১০ মার্চ, ২০২৬", en: "March 10, 2026" },
  "৫ মার্চ, ২০২৬": { bn: "৫ মার্চ, ২০২৬", en: "March 5, 2026" },
  "১ মার্চ, ২০২৬": { bn: "১ মার্চ, ২০২৬", en: "March 1, 2026" },
  // Mock event dates
  "১৫ এপ্রিল, ২০২৬": { bn: "১৫ এপ্রিল, ২০২৬", en: "April 15, 2026" },
  "২৫ এপ্রিল, ২০২৬": { bn: "২৫ এপ্রিল, ২০২৬", en: "April 25, 2026" },
  "৫ মে, ২০২৬": { bn: "৫ মে, ২০২৬", en: "May 5, 2026" },
  "১৫ মে, ২০২৬": { bn: "১৫ মে, ২০২৬", en: "May 15, 2026" },
  // Mock event times
  "বিকাল ৪:০০ - রাত ৯:০০": { bn: "বিকাল ৪:০০ - রাত ৯:০০", en: "4:00 PM - 9:00 PM" },
  "সকাল ১০:০০ - বিকাল ৩:০০": { bn: "সকাল ১০:০০ - বিকাল ৩:০০", en: "10:00 AM - 3:00 PM" },
  "সন্ধ্যা ৬:০০ - রাত ১০:০০": { bn: "সন্ধ্যা ৬:০০ - রাত ১০:০০", en: "6:00 PM - 10:00 PM" },
  "সকাল ১১:০০ - সন্ধ্যা ৭:০০": { bn: "সকাল ১১:০০ - সন্ধ্যা ৭:০০", en: "11:00 AM - 7:00 PM" },
  // Mock event locations
  "ফরিদপুর শিল্পকলা একাডেমি": { bn: "ফরিদপুর শিল্পকলা একাডেমি", en: "Faridpur Shilpakala Academy" },
  "জেলা পাবলিক লাইব্রেরি": { bn: "জেলা পাবলিক লাইব্রেরি", en: "District Public Library" },
  "মুক্তিযোদ্ধা মিলনায়তন": { bn: "মুক্তিযোদ্ধা মিলনায়তন", en: "Muktijoddha Auditorium" },
  "ফরিদপুর জেলা শিল্পকলা একাডেমি": { bn: "ফরিদপুর জেলা শিল্পকলা একাডেমি", en: "Faridpur District Shilpakala Academy" },
  // Mock event descriptions
  "বিশিষ্ট কবিদের কবিতা পাঠ ও তরুণ কবিদের কবিতা প্রতিযোগিতা।": { bn: "বিশিষ্ট কবিদের কবিতা পাঠ ও তরুণ কবিদের কবিতা প্রতিযোগিতা।", en: "Poetry readings by renowned poets and poetry competition for young poets." },
  "আধুনিক বাংলা সাহিত্যের বিভিন্ন দিক নিয়ে আলোচনা ও প্রশ্নোত্তর পর্ব।": { bn: "আধুনিক বাংলা সাহিত্যের বিভিন্ন দিক নিয়ে আলোচনা ও প্রশ্নোত্তর পর্ব।", en: "Discussion and Q&A session on various aspects of modern Bengali literature." },
  "বাউল, ভাটিয়ালি ও অন্যান্য লোকসংগীতের পরিবেশনা।": { bn: "বাউল, ভাটিয়ালি ও অন্যান্য লোকসংগীতের পরিবেশনা।", en: "Performances of Baul, Bhatiyali and other folk music." },
  "স্থানীয় শিল্পীদের চিত্রকলা ও ভাস্কর্য প্রদর্শনী।": { bn: "স্থানীয় শিল্পীদের চিত্রকলা ও ভাস্কর্য প্রদর্শনী।", en: "Painting and sculpture exhibition by local artists." },
  // Notice dates
  "২৮ মার্চ": { bn: "২৮ মার্চ", en: "Mar 28" },
  "২৫ মার্চ": { bn: "২৫ মার্চ", en: "Mar 25" },
  "২০ মার্চ": { bn: "২০ মার্চ", en: "Mar 20" },
  "১৮ মার্চ": { bn: "১৮ মার্চ", en: "Mar 18" },
  "১৫ মার্চ": { bn: "১৫ মার্চ", en: "Mar 15" },
  // Mock post authors
  "ড. আবদুল করিম": { bn: "ড. আবদুল করিম", en: "Dr. Abdul Karim" },
  "অধ্যাপক ফাতেমা বেগম": { bn: "অধ্যাপক ফাতেমা বেগম", en: "Prof. Fatema Begum" },
  "মোঃ রফিকুল ইসলাম": { bn: "মোঃ রফিকুল ইসলাম", en: "Md. Rafiqul Islam" },
  "সুফিয়া খানম": { bn: "সুফিয়া খানম", en: "Sufia Khanam" },
  "জাহিদ হাসান": { bn: "জাহিদ হাসান", en: "Zahid Hasan" },
  // Instructor label
  instructor: { bn: "প্রশিক্ষক", en: "Instructor" },
  // Site name
  siteName: { bn: "ফরিদপুর সাহিত্য পরিষদ", en: "Faridpur Shahitto Parishad" },
  siteTagline: { bn: "বাংলা সংস্কৃতির পাদপীঠ", en: "The Cradle of Bengali Culture" },
  // Courses page
  coursesSubtitle: { bn: "সেমিনার, ভাষা কোর্স ও শিক্ষা কার্যক্রম", en: "Seminars, language courses and educational programs" },
  statusOpen: { bn: "নিবন্ধন চলছে", en: "Registration Open" },
  statusOngoing: { bn: "চলমান", en: "Ongoing" },
  statusComingSoon: { bn: "শীঘ্রই আসছে", en: "Coming Soon" },
  modules: { bn: "মডিউল", en: "Modules" },
  enrolled: { bn: "জন", en: "Enrolled" },
  // Banner slides
  bannerTag1: { bn: "আসন্ন ইভেন্ট", en: "Upcoming Event" },
  bannerTitle1: { bn: "বসন্ত কবিতা উৎসব ২০২৬", en: "Spring Poetry Festival 2026" },
  bannerSub1: { bn: "আসুন কবিতার সুরে মেতে উঠি", en: "Let's celebrate with the rhythm of poetry" },
  bannerTag2: { bn: "ঘোষণা", en: "Announcement" },
  bannerTitle2: { bn: "নতুন সদস্য নিবন্ধন শুরু", en: "New Member Registration Open" },
  bannerSub2: { bn: "আজই যোগ দিন আমাদের সাহিত্য পরিবারে", en: "Join our literary family today" },
  bannerTag3: { bn: "প্রকাশনা", en: "Publication" },
  bannerTitle3: { bn: "মাসিক পত্রিকা 'সাহিত্য সুধা'", en: "Monthly Magazine 'Sahitya Sudha'" },
  bannerSub3: { bn: "এপ্রিল সংখ্যা প্রকাশিত হয়েছে", en: "April issue has been published" },
  // Notices
  notice1: { bn: "বার্ষিক সাধারণ সভার তারিখ ঘোষণা - ১৫ এপ্রিল ২০২৬", en: "Annual General Meeting Announced - April 15, 2026" },
  notice2: { bn: "নতুন সদস্য নিবন্ধন শুরু হয়েছে", en: "New member registration has started" },
  notice3: { bn: "কবিতা প্রতিযোগিতার ফলাফল প্রকাশ", en: "Poetry competition results published" },
  // Event tags
  tagUpcoming: { bn: "আসন্ন", en: "Upcoming" },
  tagRegistrationOpen: { bn: "নিবন্ধন চলছে", en: "Registration Open" },
  tagSoon: { bn: "শীঘ্রই", en: "Soon" },
  // Translate button
  translateContent: { bn: "অনুবাদ করুন", en: "Translate" },
  originalLanguage: { bn: "মূল ভাষা", en: "Original" },
  // Made with
  madeInBangladesh: { bn: "বাংলাদেশে তৈরি", en: "Made in Bangladesh" },
  // Menu label
  menu: { bn: "মেনু", en: "Menu" },
  close: { bn: "বন্ধ করুন", en: "Close" },
  navigation: { bn: "নেভিগেশন", en: "Navigation" },
  // Blog reader
  backToBlog: { bn: "ব্লগে ফিরে যান", en: "Back to Blog" },
  relatedVideo: { bn: "সংশ্লিষ্ট ভিডিও", en: "Related Video" },
  rateThisPost: { bn: "এই লেখাটি রেটিং দিন", en: "Rate this post" },
  sharePost: { bn: "শেয়ার করুন", en: "Share" },
  copyLink: { bn: "লিঙ্ক কপি করুন", en: "Copy Link" },
  comments: { bn: "মন্তব্য", en: "Comments" },
  writeComment: { bn: "আপনার মন্তব্য লিখুন...", en: "Write your comment..." },
  guestReader: { bn: "অতিথি পাঠক", en: "Guest Reader" },
  justNow: { bn: "এইমাত্র", en: "Just now" },
  postNotFound: { bn: "পোস্টটি পাওয়া যায়নি", en: "Post not found" },
  editorialBoard: { bn: "সম্পাদনা পরিষদ", en: "Editorial Board" },
  fspAuthor: { bn: "ফরিদপুর সাহিত্য পরিষদ", en: "Faridpur Shahitto Parishad" },
  lightMode: { bn: "লাইট মোড", en: "Light mode" },
  darkMode: { bn: "ডার্ক মোড", en: "Dark mode" },
  toggleLanguage: { bn: "ভাষা পরিবর্তন করুন", en: "Toggle language" },
  otpSent: { bn: "OTP পাঠানো হয়েছে", en: "OTP sent" },
  otpSentDesc: { bn: "আপনার ইমেইলে যাচাইকরণ কোড পাঠানো হয়েছে।", en: "A verification code has been sent to your email." },
  otpVerificationTitle: { bn: "OTP যাচাইকরণ", en: "OTP Verification" },
  verifyOtp: { bn: "যাচাই করুন", en: "Verify" },
  resendCode: { bn: "পুনরায় কোড পাঠান", en: "Resend code" },
  goBack: { bn: "পিছনে যান", en: "Go back" },
  verificationFailed: { bn: "যাচাই ব্যর্থ", en: "Verification failed" },
  accountVerifiedDesc: { bn: "আপনার অ্যাকাউন্ট সফলভাবে যাচাই হয়েছে।", en: "Your account has been verified successfully." },
  resendFailed: { bn: "পুনরায় পাঠাতে ব্যর্থ", en: "Resend failed" },
  codeResent: { bn: "কোড আবার পাঠানো হয়েছে", en: "Code resent" },
  pageNotFound: { bn: "পৃষ্ঠা খুঁজে পাওয়া যায়নি", en: "Page not found" },
  returnHome: { bn: "হোমে ফিরুন", en: "Return Home" },
  success: { bn: "সফল!", en: "Success!" },
  error: { bn: "ত্রুটি", en: "Error" },
  deleted: { bn: "মুছে ফেলা হয়েছে", en: "Deleted" },
  save: { bn: "সংরক্ষণ", en: "Save" },
  edit: { bn: "সম্পাদনা", en: "Edit" },
  createContent: { bn: "কন্টেন্ট তৈরি করুন", en: "Create Content" },
  postLabel: { bn: "পোস্ট", en: "Post" },
  eventLabel: { bn: "ইভেন্ট", en: "Event" },
  titleBangla: { bn: "শিরোনাম (বাংলা)", en: "Title (Bangla)" },
  titleEnglish: { bn: "শিরোনাম (ইংরেজি)", en: "Title (English)" },
  categoryLabel: { bn: "ক্যাটাগরি", en: "Category" },
  excerptLabel: { bn: "সংক্ষিপ্ত বিবরণ...", en: "Short summary..." },
  contentBody: { bn: "পোস্টের বিষয়বস্তু...", en: "Post content..." },
  publishNow: { bn: "প্রকাশ করুন", en: "Publish" },
  postNow: { bn: "পোস্ট করুন", en: "Post Now" },
  eventTitleLabel: { bn: "ইভেন্ট শিরোনাম", en: "Event Title" },
  dateLabel: { bn: "তারিখ", en: "Date" },
  timeLabel: { bn: "সময়", en: "Time" },
  locationLabel: { bn: "স্থান", en: "Location" },
  tagLabel: { bn: "ট্যাগ", en: "Tag" },
  descriptionLabel: { bn: "বিবরণ...", en: "Description..." },
  createEventLabel: { bn: "ইভেন্ট তৈরি", en: "Create Event" },
  clickToCreateContent: { bn: "উপরের বাটনে ক্লিক করে পোস্ট বা ইভেন্ট তৈরি করুন", en: "Use the buttons above to create a post or event" },
  visualEditor: { bn: "ভিজুয়াল এডিটর", en: "Visual Editor" },
  changes: { bn: "পরিবর্তন", en: "changes" },
  saved: { bn: "সংরক্ষিত!", en: "Saved!" },
  changesSaved: { bn: "পরিবর্তনগুলো সেভ হয়েছে।", en: "Your changes have been saved." },
  rotateLeft: { bn: "বামে ঘোরান", en: "Rotate left" },
  rotateRight: { bn: "ডানে ঘোরান", en: "Rotate right" },
  scaleUp: { bn: "বড় করুন", en: "Scale up" },
  scaleDown: { bn: "ছোট করুন", en: "Scale down" },
  toggleVisibility: { bn: "দৃশ্যমানতা পরিবর্তন করুন", en: "Toggle visibility" },
  reset: { bn: "রিসেট", en: "Reset" },
  profileInfo: { bn: "প্রোফাইল তথ্য", en: "Profile Information" },
  displayName: { bn: "প্রদর্শন নাম", en: "Display Name" },
  bio: { bn: "বায়ো", en: "Bio" },
  themeLabel: { bn: "থিম", en: "Theme" },
  light: { bn: "লাইট", en: "Light" },
  dark: { bn: "ডার্ক", en: "Dark" },
  permissionDenied: { bn: "অনুমতি নেই", en: "Permission denied" },
  fileSizeTooLarge: { bn: "ফাইলের আকার ২ এমবি এর কম হতে হবে।", en: "File size must be under 2 MB." },
  invalidImageType: { bn: "শুধুমাত্র JPG, PNG বা WebP ফাইল গ্রহণযোগ্য।", en: "Only JPG, PNG, or WebP files are allowed." },
  uploadFailed: { bn: "আপলোড ব্যর্থ", en: "Upload failed" },
  profileImageUpdated: { bn: "প্রোফাইল ছবি আপডেট হয়েছে।", en: "Profile image has been updated." },
  profileUpdated: { bn: "প্রোফাইল আপডেট হয়েছে।", en: "Profile has been updated." },
  coverImage: { bn: "কভার ছবি", en: "Cover Image" },
  imageUploaded: { bn: "ছবি আপলোড হয়েছে।", en: "Image uploaded successfully." },
  siteLogo: { bn: "সাইট লোগো", en: "Site Logo" },
  roleUser: { bn: "সদস্য", en: "Member" },
  roleModerator: { bn: "মডারেটর", en: "Moderator" },
  roleAdmin: { bn: "অ্যাডমিন", en: "Admin" },
  dashboard: { bn: "ড্যাশবোর্ড", en: "Dashboard" },
  postManagement: { bn: "পোস্ট ব্যবস্থাপনা", en: "Post Management" },
  eventManagement: { bn: "ইভেন্ট ব্যবস্থাপনা", en: "Event Management" },
  memberManagement: { bn: "সদস্য ব্যবস্থাপনা", en: "Member Management" },
  themeCustomization: { bn: "থিম কাস্টমাইজ", en: "Theme Customization" },
  siteSettingsLabel: { bn: "সাইট সেটিংস", en: "Site Settings" },
  recentPosts: { bn: "সাম্প্রতিক পোস্ট", en: "Recent Posts" },
  totalPosts: { bn: "মোট পোস্ট", en: "Total Posts" },
  totalEvents: { bn: "মোট ইভেন্ট", en: "Total Events" },
  totalMembers: { bn: "মোট সদস্য", en: "Total Members" },
  totalComments: { bn: "মোট মন্তব্য", en: "Total Comments" },
  noPostsYet: { bn: "কোনো পোস্ট নেই", en: "No posts yet" },
  newPost: { bn: "নতুন পোস্ট", en: "New Post" },
  editPost: { bn: "পোস্ট সম্পাদনা", en: "Edit Post" },
  tagsCommaSeparated: { bn: "ট্যাগ (কমা দিয়ে আলাদা)", en: "Tags (comma separated)" },
  featuredPost: { bn: "বিশেষ পোস্ট", en: "Featured Post" },
  publishedStatus: { bn: "প্রকাশিত", en: "Published" },
  draftStatus: { bn: "ড্রাফট", en: "Draft" },
  allPosts: { bn: "সকল পোস্ট", en: "All Posts" },
  noPostsCreateHint: { bn: "কোনো পোস্ট নেই। উপরে নতুন পোস্ট তৈরি করুন।", en: "No posts yet. Create a new post above." },
  newEvent: { bn: "নতুন ইভেন্ট", en: "New Event" },
  editEvent: { bn: "ইভেন্ট সম্পাদনা", en: "Edit Event" },
  allEventsLabel: { bn: "সকল ইভেন্ট", en: "All Events" },
  noEventsYet: { bn: "কোনো ইভেন্ট নেই", en: "No events yet" },
  noMembersYet: { bn: "কোনো সদস্য নেই", en: "No members yet" },
  noName: { bn: "নাম নেই", en: "No name" },
  openSite: { bn: "সাইটে যান", en: "Open Site" },
  appearanceSettings: { bn: "অ্যাপিয়ারেন্স সেটিংস", en: "Appearance Settings" },
  heroStyle: { bn: "হিরো স্টাইল", en: "Hero Style" },
  defaultStyle: { bn: "ডিফল্ট", en: "Default" },
  minimalStyle: { bn: "মিনিমাল", en: "Minimal" },
  cinematicStyle: { bn: "সিনেম্যাটিক", en: "Cinematic" },
  showParticles: { bn: "পার্টিকেল ইফেক্ট দেখান", en: "Show particle effect" },
  livePreview: { bn: "লাইভ প্রিভিউ", en: "Live Preview" },
  generalSettings: { bn: "সাধারণ সেটিংস", en: "General Settings" },
  siteNameBnLabel: { bn: "সাইটের নাম (বাংলা)", en: "Site Name (Bangla)" },
  siteNameEnLabel: { bn: "সাইটের নাম (ইংরেজি)", en: "Site Name (English)" },
  taglineBnLabel: { bn: "ট্যাগলাইন (বাংলা)", en: "Tagline (Bangla)" },
  taglineEnLabel: { bn: "ট্যাগলাইন (ইংরেজি)", en: "Tagline (English)" },
  contactEmailLabel: { bn: "যোগাযোগ ইমেইল", en: "Contact Email" },
  contactPhoneLabel: { bn: "যোগাযোগ ফোন", en: "Contact Phone" },
  addressBnLabel: { bn: "ঠিকানা (বাংলা)", en: "Address (Bangla)" },
  addressEnLabel: { bn: "ঠিকানা (ইংরেজি)", en: "Address (English)" },
  featureToggles: { bn: "ফিচার টগল", en: "Feature Toggles" },
  maintenanceModeLabel: { bn: "মেইনটেনেন্স মোড", en: "Maintenance Mode" },
  heritagePalette: { bn: "হেরিটেজ প্যালেট", en: "Heritage palette" },
  heritagePaletteDesc: { bn: "সাইটের প্রাইমারি, অ্যাকসেন্ট, হিরো গ্রেডিয়েন্ট, লোগোর রঙ এবং ট্যাব আইকন সেট করে।", en: "Sets the sitewide primary, accent, hero gradient, logo color, and tab icon." },
  paletteCrimson: { bn: "ক্রিমসন", en: "Crimson" },
  paletteForest: { bn: "ফরেস্ট", en: "Forest" },
  paletteRoyal: { bn: "রয়্যাল", en: "Royal" },
  paletteMarigold: { bn: "ম্যারিগোল্ড", en: "Marigold" },
  paletteMagenta: { bn: "ম্যাজেন্টা", en: "Magenta" },
  paletteMidnight: { bn: "মিডনাইট", en: "Midnight Aurora" },
  paletteSaffron: { bn: "জাফরান", en: "Saffron Glow" },
  paletteOcean: { bn: "ওশান", en: "Ocean Tide" },
  paletteRose: { bn: "গোলাপ", en: "Rose Quartz" },
  paletteEmerald: { bn: "এমারেল্ড", en: "Emerald Dynasty" },
  logoHaloIntensity: { bn: "লোগো হ্যালো ইন্টেনসিটি", en: "Logo halo intensity" },
  haloOff: { bn: "বন্ধ", en: "Off" },
  haloSubtle: { bn: "মৃদু", en: "Subtle" },
  haloNormal: { bn: "স্বাভাবিক", en: "Normal" },
  haloBold: { bn: "প্রবল", en: "Bold" },
  apply: { bn: "প্রয়োগ", en: "Apply" },
  logoDilation: { bn: "লোগো ব্যাকগ্রাউন্ড ডাইলেশন", en: "Logo background dilation" },
  logoDilationHint: { bn: "(ভেতরের ফাঁকা অংশ পূরণ করে — ০ থেকে ২০)", en: "(fills inner gaps — 0 to 20)" },
  roleChanged: { bn: "ভূমিকা পরিবর্তন হয়েছে।", en: "Role has been changed." },
  settingsUpdated: { bn: "সেটিংস আপডেট হয়েছে।", en: "Settings have been updated." },
  postSaved: { bn: "পোস্ট সংরক্ষিত হয়েছে।", en: "Post has been saved." },
  eventSaved: { bn: "ইভেন্ট সংরক্ষিত হয়েছে।", en: "Event has been saved." },
  facebookLabel: { bn: "ফেসবুক", en: "Facebook" },
  twitterXLabel: { bn: "টুইটার / X", en: "Twitter / X" },
  eventNotFound: { bn: "ইভেন্ট পাওয়া যায়নি", en: "Event not found" },
  backToEvents: { bn: "ইভেন্টে ফিরুন", en: "Back to Events" },
  eventDetails: { bn: "ইভেন্টের বিবরণ", en: "Event Details" },
  date: { bn: "তারিখ", en: "Date" },
  time: { bn: "সময়", en: "Time" },
  location: { bn: "স্থান", en: "Location" },
  courseNotFound: { bn: "কোর্স পাওয়া যায়নি", en: "Course not found" },
  backToCourses: { bn: "কোর্সে ফিরুন", en: "Back to Courses" },
  courseDescription: { bn: "কোর্সের বিবরণ", en: "Course Description" },
  courseHighlights: { bn: "কোর্সের বৈশিষ্ট্য", en: "Course Highlights" },
  duration: { bn: "সময়কাল", en: "Duration" },
  totalModules: { bn: "মোট মডিউল", en: "Total Modules" },
  searchResults: { bn: "অনুসন্ধান ফলাফল", en: "Search Results" },
  resultsFound: { bn: "টি ফলাফল পাওয়া গেছে", en: "results found" },
  noSearchResults: { bn: "কোনো ফলাফল পাওয়া যায়নি", en: "No results found" },
  searchPrompt: { bn: "অনুসন্ধান করতে কিছু লিখুন", en: "Type something to search" },
  viewAllResults: { bn: "সব ফলাফল দেখুন", en: "View all results" },
  translatingContent: { bn: "অনুবাদ হচ্ছে...", en: "Translating..." },
  "আহমেদ হোসেন": { bn: "আহমেদ হোসেন", en: "Ahmed Hossain" },
  "নাজমা আক্তার": { bn: "নাজমা আক্তার", en: "Nazma Akhter" },
  "রাকিব উদ্দিন": { bn: "রাকিব উদ্দিন", en: "Rakib Uddin" },
  "২১ মার্চ": { bn: "২১ মার্চ", en: "Mar 21" },
  "২৬ মার্চ": { bn: "২৬ মার্চ", en: "Mar 26" },
  // Members admin
  membersAdmin: { bn: "সদস্য পরিচালনা", en: "Members" },
  newMember: { bn: "নতুন সদস্য", en: "New Member" },
  editMember: { bn: "সদস্য সম্পাদনা", en: "Edit Member" },
  allMembersLabel: { bn: "সকল সদস্য", en: "All Members" },
  nameBangla: { bn: "নাম (বাংলা)", en: "Name (Bangla)" },
  nameEnglish: { bn: "নাম (ইংরেজি)", en: "Name (English)" },
  titleRoleBn: { bn: "পদবি (বাংলা)", en: "Title (Bangla)" },
  titleRoleEn: { bn: "পদবি (ইংরেজি)", en: "Title (English)" },
  bioBangla: { bn: "সংক্ষিপ্ত পরিচয় (বাংলা)", en: "Bio (Bangla)" },
  bioEnglish: { bn: "সংক্ষিপ্ত পরিচয় (ইংরেজি)", en: "Bio (English)" },
  memberRole: { bn: "ভূমিকা", en: "Role" },
  sortOrder: { bn: "ক্রম", en: "Sort Order" },
  isSenior: { bn: "সিনিয়র সদস্য", en: "Senior Member" },
  isActive: { bn: "সক্রিয়", en: "Active" },
  avatarImage: { bn: "ছবি", en: "Avatar" },
  gradientClass: { bn: "গ্রেডিয়েন্ট ক্লাস", en: "Gradient Class" },
  memberSaved: { bn: "সদস্য সংরক্ষিত হয়েছে।", en: "Member saved." },
  rolePresident: { bn: "সভাপতি", en: "President" },
  roleVp: { bn: "সহ-সভাপতি", en: "Vice President" },
  roleSecretary: { bn: "সাধারণ সম্পাদক", en: "General Secretary" },
  roleCultural: { bn: "সাংস্কৃতিক সম্পাদক", en: "Cultural Secretary" },
  roleTreasurer: { bn: "কোষাধ্যক্ষ", en: "Treasurer" },
  roleMember: { bn: "সদস্য", en: "Member" },
  // Approval & reorder
  isApproved: { bn: "অনুমোদিত", en: "Approved" },
  pending: { bn: "অপেক্ষমাণ", en: "Pending" },
  approve: { bn: "অনুমোদন", en: "Approve" },
  approvedToast: { bn: "অনুমোদন হয়েছে", en: "Approved" },
  // Asset manager
  assetManager: { bn: "অ্যাসেট ম্যানেজার", en: "Asset Manager" },
  assetName: { bn: "ছবির নাম...", en: "Image name..." },
  uploadToSlot: { bn: "আপলোড করুন", en: "Upload" },
  assetManagerHint: { bn: "প্রতিটি স্লটের জন্য ছবি আপলোড করুন। প্রথম সক্রিয় হিরো ছবি ল্যান্ডিং পেজে দেখা যাবে।", en: "Upload images per slot. The first active hero image is used on the landing page." },
  noAssetsInSlot: { bn: "এই স্লটে কোনো ছবি নেই", en: "No images in this slot" },
  inactive: { bn: "নিষ্ক্রিয়", en: "Inactive" },
  activate: { bn: "সক্রিয় করুন", en: "Activate" },
  deactivate: { bn: "নিষ্ক্রিয় করুন", en: "Deactivate" },
  copyUrl: { bn: "লিংক কপি করুন", en: "Copy URL" },
  copied: { bn: "কপি হয়েছে", en: "Copied" },
  slot_hero: { bn: "হিরো", en: "Hero" },
  slot_slider: { bn: "স্লাইডার", en: "Slider" },
  slot_course_cover: { bn: "কোর্স কভার", en: "Course Cover" },
  slot_blog_cover: { bn: "ব্লগ কভার", en: "Blog Cover" },
  slot_gallery: { bn: "গ্যালারি", en: "Gallery" },
  // Member composer
  whatsOnYourMind: { bn: "{name}, আপনি কী ভাবছেন?", en: "What's on your mind, {name}?" },
  composerBody: { bn: "আপনার পোস্টের বিস্তারিত লিখুন...", en: "Share what's on your mind..." },
  addPhoto: { bn: "ছবি যোগ করুন", en: "Add Photo" },
  cancel: { bn: "বাতিল", en: "Cancel" },
  autoPublishSenior: { bn: "তাৎক্ষণিক প্রকাশিত হবে", en: "Auto-published" },
  approvalRequired: { bn: "অনুমোদনের পর প্রকাশিত হবে", en: "Pending approval" },
  postPublished: { bn: "পোস্ট প্রকাশিত হয়েছে", en: "Your post is live" },
  postPendingApproval: { bn: "অ্যাডমিন অনুমোদনের জন্য পাঠানো হয়েছে", en: "Sent for admin approval" },
  yourRecentPosts: { bn: "আপনার সাম্প্রতিক পোস্ট", en: "Your recent posts" },
  statusPublished: { bn: "প্রকাশিত", en: "Published" },
  statusPending: { bn: "অপেক্ষমাণ", en: "Pending" },
  statusRejected: { bn: "প্রত্যাখ্যাত", en: "Rejected" },
  // Course registration
  registerForCourse: { bn: "কোর্সে নিবন্ধন", en: "Register for Course" },
  loginToRegister: { bn: "নিবন্ধনের জন্য লগইন করুন।", en: "Please log in to register." },
  alreadyRegistered: { bn: "আপনি ইতিমধ্যে নিবন্ধিত।", en: "You're already registered." },
  registrationSubmitted: { bn: "নিবন্ধন গৃহীত হয়েছে!", en: "Registration submitted!" },
  registrationNotes: { bn: "অতিরিক্ত মন্তব্য (ঐচ্ছিক)", en: "Additional notes (optional)" },
  submitRegistration: { bn: "নিবন্ধন জমা দিন", en: "Submit Registration" },
  statusLabel: { bn: "স্ট্যাটাস", en: "Status" },
  // Admin: pending posts moderation
  pendingPosts: { bn: "অপেক্ষমাণ পোস্ট", en: "Pending Posts" },
  noPendingPosts: { bn: "কোনো অপেক্ষমাণ পোস্ট নেই", en: "No pending posts" },
  reject: { bn: "প্রত্যাখ্যান", en: "Reject" },
  by: { bn: "লেখক", en: "By" },
  // Admin: settings history
  settingsHistory: { bn: "সেটিংস ইতিহাস", en: "Settings History" },
  noHistory: { bn: "কোনো ইতিহাস নেই", en: "No history yet" },
  rollback: { bn: "পুনরুদ্ধার", en: "Restore" },
  rolledBack: { bn: "পুনরুদ্ধার সম্পন্ন", en: "Restored" },
  historyHint: { bn: "গত ৯০ দিনের পরিবর্তন স্বয়ংক্রিয়ভাবে সংরক্ষিত", en: "Last 90 days of changes are kept automatically" },
  // Health check
  dbHealthy: { bn: "ডাটাবেস সংযুক্ত", en: "Database connected" },
  dbReadFailed: { bn: "ডাটাবেস পড়তে ব্যর্থ", en: "Database read failed" },
  dbWriteFailed: { bn: "ডাটাবেস লিখতে ব্যর্থ", en: "Database write failed" },
  retry: { bn: "পুনরায় চেষ্টা", en: "Retry" },
  moderation: { bn: "মডারেশন", en: "Moderation" },
  rejected: { bn: "প্রত্যাখ্যাত", en: "Rejected" },
  // Courses admin
  courseManagement: { bn: "কোর্স ব্যবস্থাপনা", en: "Course Management" },
  newCourse: { bn: "নতুন কোর্স", en: "New Course" },
  editCourse: { bn: "কোর্স সম্পাদনা", en: "Edit Course" },
  allCoursesAdmin: { bn: "সব কোর্স", en: "All Courses" },
  courseTitleBn: { bn: "শিরোনাম (বাংলা)", en: "Title (Bangla)" },
  courseTitleEn: { bn: "শিরোনাম (ইংরেজি)", en: "Title (English)" },
  instructorBn: { bn: "প্রশিক্ষক (বাংলা)", en: "Instructor (Bangla)" },
  instructorEn: { bn: "প্রশিক্ষক (ইংরেজি)", en: "Instructor (English)" },
  durationBn: { bn: "মেয়াদ (বাংলা)", en: "Duration (Bangla)" },
  durationEn: { bn: "মেয়াদ (ইংরেজি)", en: "Duration (English)" },
  modulesCount: { bn: "মডিউল সংখ্যা", en: "Modules" },
  enrolledCount: { bn: "নিবন্ধিত সংখ্যা", en: "Enrolled" },
  highlightsBn: { bn: "মূল বৈশিষ্ট্য (বাংলা, কমা দ্বারা)", en: "Highlights (Bangla, comma-separated)" },
  highlightsEnLabel: { bn: "মূল বৈশিষ্ট্য (ইংরেজি, কমা দ্বারা)", en: "Highlights (English, comma-separated)" },
  courseStatus: { bn: "অবস্থা", en: "Status" },
  noCoursesYet: { bn: "এখনো কোনো কোর্স নেই", en: "No courses yet" },
  courseSaved: { bn: "কোর্স সংরক্ষিত হয়েছে", en: "Course saved" },
  // Admin sidebar tabs (new)
  welcomeSpeechesTab: { bn: "স্বাগত বক্তব্য", en: "Welcome Speeches" },
  pageBuilderTab: { bn: "পেজ বিল্ডার", en: "Page Builder" },
  seoSettingsTab: { bn: "এসইও সেটিংস", en: "SEO Settings" },
  healthLabel: { bn: "স্বাস্থ্য", en: "Health" },
  // ThemePanel
  themeColors: { bn: "থিম রঙসমূহ", en: "Theme Colors" },
  themeColorsDesc: { bn: "সাইটে ব্যবহৃত প্রতিটি রঙ সম্পাদনা করুন। ডিফল্ট মনোক্রোম — এখানে আপনার ব্র্যান্ড প্যালেট সেট করুন।", en: "Edit every color used across the site. Defaults are pure monochrome — set your brand palette here." },
  themeSaved: { bn: "থিম সংরক্ষিত হয়েছে", en: "Theme saved" },
  themeSavedDesc: { bn: "সাইট জুড়ে রঙ আপডেট হয়েছে।", en: "Colors updated across the site." },
  resetToMono: { bn: "মনোক্রোমে রিসেট", en: "Reset to monochrome" },
  saveTheme: { bn: "থিম সংরক্ষণ", en: "Save theme" },
  // Theme tokens
  tokenBackground: { bn: "ব্যাকগ্রাউন্ড", en: "Background" },
  tokenForeground: { bn: "ফোরগ্রাউন্ড (টেক্সট)", en: "Foreground (text)" },
  tokenCard: { bn: "কার্ড", en: "Card" },
  tokenCardForeground: { bn: "কার্ড টেক্সট", en: "Card text" },
  tokenPopover: { bn: "পপওভার", en: "Popover" },
  tokenPopoverForeground: { bn: "পপওভার টেক্সট", en: "Popover text" },
  tokenPrimary: { bn: "প্রাইমারি", en: "Primary" },
  tokenPrimaryForeground: { bn: "প্রাইমারি টেক্সট", en: "Primary text" },
  tokenSecondary: { bn: "সেকেন্ডারি", en: "Secondary" },
  tokenSecondaryForeground: { bn: "সেকেন্ডারি টেক্সট", en: "Secondary text" },
  tokenMuted: { bn: "মিউটেড", en: "Muted" },
  tokenMutedForeground: { bn: "মিউটেড টেক্সট", en: "Muted text" },
  tokenAccent: { bn: "অ্যাকসেন্ট", en: "Accent" },
  tokenAccentForeground: { bn: "অ্যাকসেন্ট টেক্সট", en: "Accent text" },
  tokenDestructive: { bn: "ডেস্ট্রাকটিভ", en: "Destructive" },
  tokenDestructiveForeground: { bn: "ডেস্ট্রাকটিভ টেক্সট", en: "Destructive text" },
  tokenBorder: { bn: "বর্ডার", en: "Border" },
  tokenInput: { bn: "ইনপুট", en: "Input" },
  tokenRing: { bn: "রিং (ফোকাস)", en: "Ring (focus)" },
  tokenGold: { bn: "গোল্ড", en: "Gold" },
  tokenGoldLight: { bn: "গোল্ড লাইট", en: "Gold light" },
  tokenGoldForeground: { bn: "গোল্ড টেক্সট", en: "Gold text" },
  tokenCrimson: { bn: "ক্রিমসন", en: "Crimson" },
  tokenCrimsonDark: { bn: "ক্রিমসন ডার্ক", en: "Crimson dark" },
  tokenCrimsonLight: { bn: "ক্রিমসন লাইট", en: "Crimson light" },
  tokenCrimsonForeground: { bn: "ক্রিমসন টেক্সট", en: "Crimson text" },
  tokenForest: { bn: "ফরেস্ট", en: "Forest" },
  tokenForestLight: { bn: "ফরেস্ট লাইট", en: "Forest light" },
  tokenForestForeground: { bn: "ফরেস্ট টেক্সট", en: "Forest text" },
  tokenSuccess: { bn: "সফল", en: "Success" },
  tokenSuccessForeground: { bn: "সফল টেক্সট", en: "Success text" },
  tokenWarning: { bn: "সতর্কতা", en: "Warning" },
  tokenWarningForeground: { bn: "সতর্কতা টেক্সট", en: "Warning text" },
  // HomeBannersPanel
  homeBannersTitle: { bn: "হোম ব্যানার", en: "Home banners" },
  homeBannersDesc: { bn: "হোম পেজের শীর্ষে ঘূর্ণায়মান হিরো স্লাইড।", en: "Rotating hero slides shown at the top of the home page." },
  newLabel: { bn: "নতুন", en: "New" },
  bannerTagBn: { bn: "ট্যাগ (বাংলা)", en: "Tag (Bangla)" },
  bannerTagEn: { bn: "ট্যাগ (ইংরেজি)", en: "Tag (English)" },
  bannerTitleBn: { bn: "শিরোনাম (বাংলা)", en: "Title (Bangla)" },
  bannerTitleEn: { bn: "শিরোনাম (ইংরেজি)", en: "Title (English)" },
  bannerSubtitleBn: { bn: "সাবটাইটেল (বাংলা)", en: "Subtitle (Bangla)" },
  bannerSubtitleEn: { bn: "সাবটাইটেল (ইংরেজি)", en: "Subtitle (English)" },
  bannerLinkUrl: { bn: "লিংক URL (ঐচ্ছিক)", en: "Link URL (optional)" },
  backgroundImage: { bn: "ব্যাকগ্রাউন্ড ছবি", en: "Background image" },
  updateLabel: { bn: "আপডেট", en: "Update" },
  createLabel: { bn: "তৈরি", en: "Create" },
  loadingLabel: { bn: "লোড হচ্ছে...", en: "Loading..." },
  noBannersYet: { bn: "কোনো ব্যানার নেই।", en: "No banners yet." },
  // SpeechesPanel
  welcomePopupSettings: { bn: "ওয়েলকাম পপআপ সেটিংস", en: "Welcome Popup Settings" },
  enabledLabel: { bn: "চালু", en: "Enabled" },
  cooldownMinutes: { bn: "কুলডাউন (মিনিট)", en: "Cooldown (minutes)" },
  editSpeech: { bn: "বক্তব্য সম্পাদনা", en: "Edit Speech" },
  newSpeech: { bn: "নতুন বক্তব্য", en: "New Speech" },
  uploadPhoto: { bn: "ছবি আপলোড", en: "Upload Photo" },
  noSpeechesYet: { bn: "এখনো কোনো বক্তব্য নেই। উপরে যোগ করুন।", en: "No speeches yet. Add one above." },
  // SeoPanel
  pagesWithoutSeo: { bn: "এসইও ছাড়া পেজ", en: "Pages without SEO" },
  allPagesHaveSeo: { bn: "সব পেজে এসইও এন্ট্রি আছে।", en: "All known pages have SEO entries." },
  newSeoEntry: { bn: "নতুন এসইও এন্ট্রি", en: "New SEO Entry" },
  editSeoEntry: { bn: "এসইও সম্পাদনা", en: "Edit SEO" },
  hideFromSearch: { bn: "সার্চ ইঞ্জিন থেকে লুকান (noindex)", en: "Hide from search engines (noindex)" },
  configuredPages: { bn: "কনফিগার করা পেজ", en: "Configured pages" },
  noSeoEntries: { bn: "এখনো কোনো এসইও এন্ট্রি নেই।", en: "No SEO entries yet." },
  // PageBuilderPanel
  customPages: { bn: "কাস্টম পেজ", en: "Custom Pages" },
  newPage: { bn: "নতুন পেজ", en: "New Page" },
  editPage: { bn: "পেজ সম্পাদনা", en: "Edit Page" },
  noCustomPages: { bn: "এখনো কোনো কাস্টম পেজ নেই।", en: "No custom pages yet." },
  showInNav: { bn: "মেনুতে দেখান", en: "Show in nav" },
  inNav: { bn: "মেনুতে", en: "in nav" },
  contentBlocks: { bn: "কন্টেন্ট ব্লক", en: "Content blocks" },
  updatePage: { bn: "পেজ আপডেট", en: "Update Page" },
  createPage: { bn: "পেজ তৈরি", en: "Create Page" },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LangContextType>({
  lang: "bn",
  setLang: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const stored = localStorage.getItem("fsp-lang");
    return (stored as Lang) || "bn";
  });

  const handleSetLang = (l: Lang) => {
    setLang(l);
    localStorage.setItem("fsp-lang", l);
  };

  const t = (key: string) => {
    const entry = translations[key];
    if (!entry) return key;
    return entry[lang];
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
