// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thvxiskgrndguzfjcvrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodnhpc2tncm5kZ3V6ZmpjdnJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4ODUyNTcsImV4cCI6MjA5MDQ2MTI1N30.oPgdzHXzLysjnS6fBo6fpMSqd_oQggg6SEfYmZl6PQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});